### ISSUE TITLE
:sparkles: FEAT. 할루시네이션 검증

### ISSUE THREAD

**Issue by junhaa** [SWOnCampus/AI#16]
# 📝 Preview
RAG 입력 데이터와 LLM 생성 내용에 대한 할루시네이션 검증

# ✅ Todo
- [x] RAG 입력 데이터와 LLM 생성 내용 문장 임베딩
- [x] 임베딩 된 데이터를 scipy로 코사인 유사도 검증
- [x] BERT-score 기반으로 Hallucination 검증

# 📌 Remark
